
let id:number=1
export const arr: string[] = [
  "Wireless Mechanical Keyboard",
  "5TB External Hard Drive",
  "Ceramic Coffee Mug Set (4)",
  "Noise-Cancelling Over-Ear Headphones",
  "High-Performance Blender",
  "Smart Watch with GPS",
  "Organic Cotton T-Shirt (Large)",
    "Wireless Mechanical Keyboard",
  "5TB External Hard Drive",
  "Ceramic Coffee Mug Set (4)",
  "Noise-Cancelling Over-Ear Headphones",
  "High-Performance Blender",
  "Smart Watch with GPS",
  "Organic Cotton T-Shirt (Large)",
    "Wireless Mechanical Keyboard",
  "5TB External Hard Drive",
  "Ceramic Coffee Mug Set (4)",
  "Noise-Cancelling Over-Ear Headphones",
  "High-Performance Blender",
  "Smart Watch with GPS",
  "Organic Cotton T-Shirt (Large)",
    "Wireless Mechanical Keyboard",
  "5TB External Hard Drive",
  "Ceramic Coffee Mug Set (4)",
  "Noise-Cancelling Over-Ear Headphones",
  "High-Performance Blender",
  "Smart Watch with GPS",
  "Organic Cotton T-Shirt (Large)",
]